config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books do
    resources :reviews
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  self.primary_key = "isbn"
  has_many :reviews, dependent: :destroy
  has_many :bookcases, dependent: :destroy
end

app/models/bookcase.rb
class Bookcase < ApplicationRecord
  belongs_to :user
  belongs_to :book, primary_key: "isbn"
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book, primary_key: "isbn"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :reviews, dependent: :destroy
  has_many :bookcases, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
  
  def show
    @book = Book.find(params[:id])
    @review = Review.new
    @reviews = @book.reviews.all
  end
  
  def new
    @books = []
    @title = params[:title]
    if @title.present?
      results = RakutenWebService::Books::Book.search({
        title: @title,
        booksGenreId: '001004',
        hits: 20,
      })

      results.each do |result|
        book = Book.new(read(result))
        @books << book
      end
    end
  end
  
  def create
    @book = Book.find_or_initialize_by(isbn: params[:isbn])

    unless @book.persisted?
      results = RakutenWebService::Books::Book.search(isbn: @book.isbn)
      @book = Book.new(read(results.first))
      @book.save
      redirect_to books_path
    end
  end
  
  private
  
  def read(result)
    title = result['title']
    url = result['itemUrl']
    isbn = result['isbn']
    image_url = result['mediumImageUrl'].gsub('?_ex=120x120', '')
    {
      title: title,
      url: url,
      isbn: isbn,
      image_url: image_url,
    }
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @review = Review.new(reviews_params)
    @review.book_id = @book.id
    @review.user_id = current_user.id
    if @review.save!
      redirect_to book_path(@book)
    else
      redirect_to books_path
    end 
  end 
  
  private
  
  def reviews_params
    params.require(:review).permit(:impression)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/index.html.erb
<% @books.each do |book| %>
  <%= image_tag book.image_url %>
  <%= link_to book.title, book_path(book) %>
  <%= book.author %>
<% end %>

app/views/books/new.html.erb
<%= form_tag(new_book_path, method: :get, class: 'form-inline') do %>
  <%= text_field_tag :title, @title, class: 'form-control', placeholder:'書籍タイトル', size: 40 %>
  <%= submit_tag '商品を検索', class: 'btn'%>
<% end %>
<% if @books %>
  <% @books.each do |book| %>
    <img src="<%= book.image_url %>" alt="">
    <p><%= book.title %></p>
    <%= form_tag(books_path, method: :post) do %>
      <%= hidden_field_tag :isbn, book.isbn %>
      <%= submit_tag 'save' %>
    <% end %>
  <% end %>
<% end %>

app/views/books/show.html.erb
<%= image_tag @book.image_url %>
<%= @book.title %>
<%= @book.author %>

  <div class="row mt-3">
    <div class="col-md-12 col-sm-12">
    <%= form_with model: [@book, @review], url: book_reviews_path(book_id: @book.id), method: :post do |f| %>
    <div class="row mt-3">
      <div class="col-md-8 offset-md-2">
        <%= f.text_area :impression, rows: '3', placeholder: "コメントをここに入力してください。",class: "col-md-12" %>
      </div>
      <div class="col-md-2 mt-4  text-center">
        <%= f.submit "Submit", class: "submit_btn" %>
      </div>
    </div>
    <% end %>
    </div>
  </div>
  <% @reviews.each do |comment| %>
  <div class="row mt-1">
    <div class="col-md-11 offset-md-1 parent">
      <p class="fs-1 child"><%= comment.impression %></p>
    </div>
  </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PFB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>